export const TABLE_RESIZE = 'TABLE_RESIZE';
export const CHANGE_TEXT = 'CHANGE_TEXT';
export const APPLY_STYLE = 'APPLY_STYLE';
export const CHANGE_STYLES = 'CHANGE_STYLES';
export const SET_CURRENT_CELL = 'SET_CURRENT_CELL';
export const CHANGE_TITLE = 'CHANGE_TITLE';
